### ISSUE TITLE
Target Mapping/Tile Restriction based on User Roles

### ISSUE THREAD

**Issue by attilaberencsi** [SAP-samples/btp-cf-cap-multitenant-susaas#24]
Hi SuSaaS Team,

I am getting this dialog when accessing the Manage Users Tile

![image](https://user-images.githubusercontent.com/20442467/226384654-bbbfc929-7c4e-480e-840b-cd788b312aee.png)

I understood the reason, this is because the user is not Admin, just has the Member role, despite he can see the Admin Group/Manage Users tile.

Can we restrict the visibility of tiles/groups/target mappings based on the Role Collections we defined to avoid user confusion ?

We have the fioriSandboxConfig.json/js files. Can we make the launchpad config dynamic using the js script (we have a user api call already ) or use a binding in the json file like this

![image](https://user-images.githubusercontent.com/20442467/226386961-298bf016-b9c1-44b5-a82c-c0ffcd42514d.png)

and call to an API during UI5 bootstrapping and setting the ui5 model with visibility configurations ?

Would it be actually acceptable such for production scenario, or we have to expose the encapsulated applications differently to a launchpad service/ work zone in production cases ?

Is actually possible for example to create the frontends in separate projects for SaaS solutions and manage the tile visibility by launchpad service / work zone  authorizations ?

Thank You, 
Best regards
Attila

**Comment by martinfrick** [comment]
Hi @attilaberencsi,

haha nice idea actually! You're keeping us busy :) Actually we didn't want to blow up this mock launchpad thing even more than we already did... Still, if you are willing to go down that rabbit hole, feel free to give it a try and shoot over a pull request! :) Then we can add it to the repository! Otherwise, we can put it on our nice-to-have list, which comes after a veeerrryyy long must-have list! 

And yes, as correctly noticed, the correct way would be using Work Zone / Launchpad, still as the respective multitenancy support is not officially released, for now I suggest to setup a custom home-page for productive scenarios! The sandbox is probably not a comparable replacement for a real Work Zone / Launchpad in this case. 

Appreciate! 
Martin

**Comment by attilaberencsi** [comment]
Hi Martin! 
I hope I can figure out something elegant as this repo to fit in :), thank You !
Best regards,Attila
